// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlhalyxxslkzkuztxiws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsaGFseXh4c2xremt1enR4aXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTg1NTEsImV4cCI6MjA2MzM5NDU1MX0.RoEzrCk1uBOebxTgqqmONxgmxBlvVwBCSKiAev2Fs_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);